In [200]:
import pandas as pd
!pip install --user xlrd

Requirement already satisfied: xlrd in c:\users\james\appdata\roaming\python\python38\site-packages (2.0.1)

In [201]:
matches = pd.read_csv("matches.csv")
matches.shape

(636, 18)

In [202]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [203]:
delivs = pd.read_csv("https://github.com/WooTechnology/ipl-saga/raw/main/Datasets/deliveries.csv")
delivs.shape

(179078, 21)

In [204]:
delivs.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [205]:
delivs.tail()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [206]:
list(delivs.columns)

['match_id',
 'inning',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'batsman',
 'non_striker',
 'bowler',
 'is_super_over',
 'wide_runs',
 'bye_runs',
 'legbye_runs',
 'noball_runs',
 'penalty_runs',
 'batsman_runs',
 'extra_runs',
 'total_runs',
 'player_dismissed',
 'dismissal_kind',
 'fielder']

In [207]:
auct = pd.read_excel("https://github.com/WooTechnology/ipl-saga/raw/main/Datasets/cricket.xls", sheet_name = "Sheet1")
auct.shape

(133, 41)

In [208]:
auct.head()

,Variable Tag,Is Captain(1=yes),Is Wktkeeper(1=Yes),Nationality(1=Overseas),Name,Team,IPL 4 Franchise,Player cost USD,matches,innings played,...,Is star bowler,wkts taken,Best innings bowling,best match bowling,Bowling average,Bowling econ,sr,4w,5w,10 wicket hauls
0,1.0,0.0,0.0,1,Aiden Blizzard,Australia,Mumbai Indians,20000.0,40.0,40.0,...,0.0,0,-,-,0.00,10,-,0,0,0
1,2.0,0.0,0.0,1,Jonathan Vandiar,South Africa,Royal Challengers Bangalore,20000.0,18.0,18.0,...,0.0,-,-,-,0.00,-,-,-,-,-
2,3.0,0.0,0.0,1,Nathan Rimmington,Australia,Kings XI Punjab,20000.0,23.0,8.0,...,0.0,31,2027-05-01 00:00:00,2027-05-01 00:00:00,18.16,7.24,15,0,1,0
3,4.0,0.0,0.0,1,Rilee Rossouw,South Africa,Royal Challengers Bangalore,20000.0,20.0,20.0,...,0.0,-,-,-,0.00,-,-,-,-,-
4,5.0,0.0,0.0,1,Robert Frylinck,South Africa,Delhi Daredevils,20000.0,25.0,22.0,...,0.0,26,1931-04-01 00:00:00,1931-04-01 00:00:00,23.96,7.5,19.1,1,0,0

In [209]:
auct.tail()

,Variable Tag,Is Captain(1=yes),Is Wktkeeper(1=Yes),Nationality(1=Overseas),Name,Team,IPL 4 Franchise,Player cost USD,matches,innings played,...,Is star bowler,wkts taken,Best innings bowling,best match bowling,Bowling average,Bowling econ,sr,4w,5w,10 wicket hauls
128,129.0,1.0,0.0,0,Gautam Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,NaN,NaN,NaN,Retained players cost is taken as the cost ded...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [210]:
auct = auct.drop([129, 130, 131, 132])

In [211]:
auct.tail()

,Variable Tag,Is Captain(1=yes),Is Wktkeeper(1=Yes),Nationality(1=Overseas),Name,Team,IPL 4 Franchise,Player cost USD,matches,innings played,...,Is star bowler,wkts taken,Best innings bowling,best match bowling,Bowling average,Bowling econ,sr,4w,5w,10 wicket hauls
124,125.0,0.0,0.0,0,Irfan Pathan,India,Delhi Daredevils,1900000.0,83.0,67.0,...,1.0,89,2027-04-01 00:00:00,2027-04-01 00:00:00,24.29,7.65,19,1,0,0
125,126.0,0.0,0.0,0,Rohit Sharma,India,Mumbai Indians,2000000.0,97.0,91.0,...,0.0,26,2011-06-04 00:00:00,2011-06-04 00:00:00,25.19,7.44,20.3,1,0,0
126,127.0,0.0,1.0,0,Robin Uthappa,India,Pune Warriors,2100000.0,93.0,87.0,...,0.0,-,-,-,0.00,-,-,-,-,-
127,128.0,0.0,0.0,0,Yusuf Pathan,India,Kolkata Knight Riders,2100000.0,90.0,82.0,...,0.0,67,2011-10-04 00:00:00,2011-10-04 00:00:00,24.50,7.46,19.7,2,0,0
128,129.0,1.0,0.0,0,Gautam Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,...,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN

In [212]:
list(auct.columns)

['Variable Tag',
 'Is Captain(1=yes)',
 'Is Wktkeeper(1=Yes)',
 'Nationality(1=Overseas)',
 'Name',
 'Team',
 'IPL 4 Franchise',
 'Player cost USD',
 'matches',
 'innings played',
 'no',
 'runs scored',
 'highest score',
 'Is star batsman',
 'Is batsman',
 'Batting avg',
 'Balls faced',
 'Strike rate',
 '100 runs made',
 '50 runs made',
 '4s',
 '6s',
 'Catches per match',
 'Catches taken',
 'stumping made',
 'Unnamed: 25',
 'matches played',
 'innings played.1',
 'Is bowler?',
 'Number of balls bowled',
 'runs given',
 'Is star bowler',
 'wkts taken',
 'Best innings bowling',
 'best match bowling',
 'Bowling average',
 'Bowling econ',
 'sr',
 '4w',
 '5w',
 '10 wicket hauls']

In [213]:
auct.set_index("Variable Tag", inplace=True)

In [214]:
auct.head()

,Is Captain(1=yes),Is Wktkeeper(1=Yes),Nationality(1=Overseas),Name,Team,IPL 4 Franchise,Player cost USD,matches,innings played,no,...,Is star bowler,wkts taken,Best innings bowling,best match bowling,Bowling average,Bowling econ,sr,4w,5w,10 wicket hauls
Variable Tag,,,,,,,,,,,,,,,,,,,,,
1.0,0.0,0.0,1,Aiden Blizzard,Australia,Mumbai Indians,20000.0,40.0,40.0,3.0,...,0.0,0,-,-,0.00,10,-,0,0,0
2.0,0.0,0.0,1,Jonathan Vandiar,South Africa,Royal Challengers Bangalore,20000.0,18.0,18.0,1.0,...,0.0,-,-,-,0.00,-,-,-,-,-
3.0,0.0,0.0,1,Nathan Rimmington,Australia,Kings XI Punjab,20000.0,23.0,8.0,5.0,...,0.0,31,2027-05-01 00:00:00,2027-05-01 00:00:00,18.16,7.24,15,0,1,0
4.0,0.0,0.0,1,Rilee Rossouw,South Africa,Royal Challengers Bangalore,20000.0,20.0,20.0,0.0,...,0.0,-,-,-,0.00,-,-,-,-,-
5.0,0.0,0.0,1,Robert Frylinck,South Africa,Delhi Daredevils,20000.0,25.0,22.0,8.0,...,0.0,26,1931-04-01 00:00:00,1931-04-01 00:00:00,23.96,7.5,19.1,1,0,0

In [235]:
in_2010 = matches.query('season==2010')
len(in_2010)

60

In [216]:
in_2010.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
229,230,2010,Kolkata,2010-04-19,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,bat,normal,0,Kolkata Knight Riders,0,9,M Kartik,Eden Gardens,BG Jerling,RE Koertzen,NaN
230,231,2010,Mumbai,2010-04-21,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Mumbai Indians,35,0,KA Pollard,Dr DY Patil Sports Academy,BR Doctrove,RB Tiffin,NaN
231,232,2010,Mumbai,2010-04-22,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,bat,normal,0,Chennai Super Kings,38,0,DE Bollinger,Dr DY Patil Sports Academy,BR Doctrove,RB Tiffin,NaN
232,233,2010,Mumbai,2010-04-24,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,normal,0,Royal Challengers Bangalore,0,9,A Kumble,Dr DY Patil Sports Academy,RE Koertzen,SJA Taufel,NaN
233,234,2010,Mumbai,2010-04-25,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Chennai Super Kings,22,0,SK Raina,Dr DY Patil Sports Academy,RE Koertzen,SJA Taufel,NaN

In [218]:
retained = [0]*129
auct["Retained"] = retained

In [219]:
def is_retained(string):
    string = str(string).split(" ")
    if string[-1] == "(retained)":
        return 1
    else:
        return 0
        
auct["Retained"] = auct["Name"].apply(is_retained)

In [220]:
def rename(string):
    string = str(string).split(" ")
    new_string = ""
    if len(string) == 2:
        new_string += string[1]
    elif len(string) == 3 and string[2] != "(retained)":
        new_string += string[2]
    elif len(string) == 3 and string[2] == "(retained)":
        new_string += string[1]
    elif len(string) == 4:
        new_string += string[3]
    return new_string
    
auct["Name"] = auct["Name"].apply(rename)
list(auct["Name"])

['Blizzard',
 'Vandiar',
 'Rimmington',
 'Rossouw',
 'Frylinck',
 'Birt',
 'Bailey',
 'Wath',
 'Pomersbasch',
 'Henriques',
 'Merwe',
 'Klinger',
 'McDonald',
 'Lumb',
 'Randiv',
 'Perera',
 'Theron',
 'Thomas',
 'Hilfenhaus',
 'Ingram',
 'Mascarenhas',
 'Franklin',
 'Taylor',
 'Wade',
 'McCullum',
 'Kulasekara',
 'Saha',
 'McKay',
 'Plessis',
 'Kaif',
 'Langeveldt',
 'Ryder',
 'Sharma',
 'Doeschate',
 'Parnell',
 'Jacobs',
 'Bravo',
 'Shah',
 'Styris',
 'Smith',
 'Agarkar',
 'Tyagi',
 'Unadkat',
 'Collingwood',
 'Ojha',
 'Paine',
 'Gony',
 'Patel',
 'Finch',
 'Mishra',
 'Ferguson',
 'Duminy',
 'Tait',
 'Dhawan',
 'Haddin',
 'Harris',
 'Morgan',
 'Hopes',
 'Dinda',
 'Lee',
 'Kartik',
 'Marsh',
 'Broad',
 'Laxman',
 'Hodge',
 'Hussey',
 'Hasan',
 'Sharma',
 'McCullum',
 'Tiwary',
 'Morkel',
 'Kumar',
 'Morkel',
 'Smith',
 'Balaji',
 'Malinga',
 'Ojha',
 'Dravid',
 'Singh',
 'Vettori',
 'Nannes',
 'Pietersen',
 'Dilshan',
 'Pujara',
 'Bollinger',
 'Sangakkara',
 'Patel',
 'Rao',
 'Warner',
 'Nayar',
 'Kumar',
 'Symonds',
 'Nehra',
 'Ashwin',
 'Badrinath',
 'Gilchrist',
 'Christian',
 'Karthik',
 'Pollard',
 'Vijay',
 'Chawla',
 '',
 'Khan',
 'Mathews',
 'Botha',
 'Jadeja',
 'Taylor',
 'Villiers',
 'White',
 'Kallis',
 'Muralitharan',
 'Steyn',
 'Singh',
 'Watson',
 'Raina',
 'Hussey',
 'Jayawardene',
 'Tiwary',
 'Dhoni',
 'Tendulkar',
 'Warne',
 'Kohli',
 'Sehwag',
 'Singh',
 'Pathan',
 'Sharma',
 'Uthappa',
 'Pathan',
 'Gambhir']

In [221]:
def surname(string):
    string = str(string).split(" ")
    new_string = ""
    if len(string) == 2:
        new_string += string[1]
    return new_string

In [222]:
delivs["batsman"] = delivs["batsman"].apply(surname)
list(delivs["batsman"])

['Warner',
 'Warner',
 'Warner',
 'Warner',
 'Warner',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Warner',
 'Warner',
 'Warner',
 'Warner',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Singh',
 'Singh',
 'Henriques',
 'Singh',
 'Singh',
 'Henriques',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Henriques',
 'Singh',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Singh',
 'Singh',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Singh',
 'Hooda',
 'Singh',
 'Hooda',
 'Hooda',
 'Singh',
 'Singh',
 'Singh',
 'Hooda',
 'Hooda',
 'Hooda',
 'Hooda',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Hooda',
 'Hooda',
 'Hooda',
 'Singh',
 'Singh',
 'Singh',
 'Cutting',
 'Hooda',
 'Cutting',
 'Hooda',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Gayle',
 'Gayle',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Gayle',
 'Gayle',
 'Gayle',
 'Singh',
 'Singh',
 'Gayle',
 'Singh',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Singh',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Head',
 'Head',
 'Gayle',
 'Gayle',
 'Gayle',
 'Head',
 'Head',
 'Jadhav',
 'Head',
 'Head',
 'Head',
 'Jadhav',
 'Head',
 'Jadhav',
 'Head',
 'Jadhav',
 'Jadhav',
 'Jadhav',
 'Head',
 'Jadhav',
 'Jadhav',
 'Jadhav',
 'Head',
 'Head',
 'Jadhav',
 'Head',
 'Head',
 'Jadhav',
 'Head',
 'Jadhav',
 'Jadhav',
 'Head',
 'Jadhav',
 'Jadhav',
 'Jadhav',
 'Jadhav',
 'Head',
 'Head',
 'Jadhav',
 'Watson',
 'Head',
 'Head',
 'Watson',
 'Watson',
 'Head',
 'Head',
 'Watson',
 'Baby',
 'Baby',
 'Watson',
 'Baby',
 'Watson',
 'Binny',
 'Binny',
 'Watson',
 'Binny',
 'Binny',
 'Binny',
 'Watson',
 'Binny',
 'Binny',
 'Binny',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Binny',
 'Watson',
 'Watson',
 'Binny',
 'Aravind',
 'Watson',
 'Watson',
 'Watson',
 'Aravind',
 'Chahal',
 'Chahal',
 'Mills',
 'Chahal',
 'Chahal',
 'Mills',
 'Mills',
 'Chahal',
 'Chahal',
 'Chahal',
 'Choudhary',
 'Choudhary',
 'Patel',
 'Patel',
 'Patel',
 'Buttler',
 'Patel',
 'Patel',
 'Patel',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Patel',
 'Patel',
 'Sharma',
 'Sharma',
 'Buttler',
 'Sharma',
 'Sharma',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Sharma',
 'Sharma',
 'Sharma',
 'Rana',
 'Buttler',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rana',
 'Rayudu',
 'Rana',
 'Rana',
 'Rana',
 'Rayudu',
 'Rana',
 'Rana',
 'Rayudu',
 'Rana',
 'Rana',
 'Rayudu',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rayudu',
 'Rana',
 'Rana',
 'Rana',
 'Rana',
 'Rayudu',
 'Pandya',
 'Rana',
 'Pandya',
 'Rana',
 'Rana',
 'Pandya',
 'Rana',
 'Rana',
 'Pandya',
 'Rana',
 'Rana',
 'Pandya',
 'Rana',
 'Pandya',
 'Rana',
 'Pollard',
 'Rana',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pollard',
 'Rana',
 'Rana',
 'Pollard',
 'Pollard',
 'Pollard',
 'Rana',
 'Pandya',
 'Pandya',
 'Pollard',
 'Pollard',
 'Pandya',
 'Pollard',
 'Pandya',
 'Pollard',
 'Pollard',
 'Pandya',
 'Pandya',
 'Pollard',
 'Pollard',
 'Pandya',
 'Pandya',
 'Pollard',
 'Pandya',
 'Pollard',
 'Southee',
 'Pandya',
 'Southee',
 'Southee',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Rahane',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Agarwal',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Agarwal',
 'Agarwal',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Smith',
 'Stokes',
 'Stokes',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Stokes',
 'Smith',
 'Smith',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Smith',
 'Smith',
 'Stokes',
 'Smith',
 'Smith',
 'Stokes',
 'Stokes',
 'Smith',
 'Dhoni',
 'Smith',
 'Smith',
 'Smith',
 'Dhoni',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Dhoni',
 'Dhoni',
 'Smith',
 'Smith',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Dhoni',
 'Dhoni',
 'Dhoni',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Smith',
 'Smith',
 'Roy',
 'Roy',
 'Roy',
 'Roy',
 'Roy',
 'Roy',
 'McCullum',
 'Roy',
 'Roy',
 'Roy',
 'Roy',
 'Roy',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'Roy',
 'McCullum',
 'Roy',
 'Raina',
 'Raina',
 'McCullum',
 'McCullum',
 'McCullum',
 'Raina',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'McCullum',
 'McCullum',
 'Raina',
 'McCullum',
 'McCullum',
 'McCullum',
 'Raina',
 'McCullum',
 'McCullum',
 'Raina',
 'McCullum',
 'Raina',
 'McCullum',
 'Finch',
 'Raina',
 'Finch',
 'Finch',
 'Raina',
 'Raina',
 'Finch',
 'Finch',
 'Finch',
 'Raina',
 'Finch',
 'Raina',
 'Finch',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Karthik',
 'Raina',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Rahane',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Stokes',
 'Smith',
 'Stokes',
 'Smith',
 'Stokes',
 'Smith',
 'Smith',
 'Smith',
 'Stokes',
 'Dhoni',
 'Dhoni',
 'Dhoni',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Dhoni',
 'Dhoni',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Dhoni',
 'Dhoni',
 'Stokes',
 'Dhoni',
 'Dhoni',
 'Stokes',
 'Stokes',
 'Dhoni',
 'Dhoni',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Christian',
 'Christian',
 'Tiwary',
 'Christian',
 'Tiwary',
 'Tiwary',
 'Christian',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Tiwary',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Vohra',
 'Amla',
 'Vohra',
 'Vohra',
 'Vohra',
 'Vohra',
 'Amla',
 'Vohra',
 'Vohra',
 'Amla',
 'Vohra',
 'Vohra',
 'Amla',
 'Vohra',
 'Vohra',
 'Amla',
 'Saha',
 'Saha',
 'Saha',
 'Saha',
 'Amla',
 'Amla',
 'Saha',
 'Amla',
 'Amla',
 'Saha',
 'Saha',
 'Saha',
 'Amla',
 'Saha',
 'Patel',
 'Amla',
 'Patel',
 'Patel',
 'Patel',
 'Amla',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Amla',
 'Amla',
 'Patel',
 'Amla',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Amla',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Gayle',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Gayle',
 'Gayle',
 'Gayle',
 'Watson',
 'Watson',
 'Gayle',
 'Gayle',
 'Gayle',
 'Watson',
 'Watson',
 'Gayle',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Singh',
 'Singh',
 'Watson',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Jadhav',
 'Watson',
 'Jadhav',
 ...]

In [223]:
delivs["non_striker"] = delivs["non_striker"].apply(surname)
list(delivs["non_striker"])

['Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Warner',
 'Warner',
 'Warner',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Dhawan',
 'Henriques',
 'Henriques',
 'Singh',
 'Henriques',
 'Henriques',
 'Singh',
 'Henriques',
 'Henriques',
 'Singh',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Singh',
 'Henriques',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Henriques',
 'Henriques',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Hooda',
 'Singh',
 'Hooda',
 'Singh',
 'Singh',
 'Hooda',
 'Hooda',
 'Hooda',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Hooda',
 'Hooda',
 'Hooda',
 'Hooda',
 'Singh',
 'Singh',
 'Singh',
 'Hooda',
 'Hooda',
 'Hooda',
 'Hooda',
 'Cutting',
 'Hooda',
 'Cutting',
 'Hooda',
 'Hooda',
 'Hooda',
 'Hooda',
 'Singh',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Gayle',
 'Gayle',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Gayle',
 'Gayle',
 'Singh',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Gayle',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Head',
 'Head',
 'Head',
 'Jadhav',
 'Jadhav',
 'Head',
 'Jadhav',
 'Jadhav',
 'Jadhav',
 'Head',
 'Jadhav',
 'Head',
 'Jadhav',
 'Head',
 'Head',
 'Head',
 'Jadhav',
 'Head',
 'Head',
 'Head',
 'Jadhav',
 'Jadhav',
 'Head',
 'Jadhav',
 'Jadhav',
 'Head',
 'Jadhav',
 'Head',
 'Head',
 'Jadhav',
 'Head',
 'Head',
 'Head',
 'Head',
 'Jadhav',
 'Jadhav',
 'Head',
 'Head',
 'Watson',
 'Watson',
 'Head',
 'Head',
 'Watson',
 'Watson',
 'Baby',
 'Watson',
 'Watson',
 'Baby',
 'Watson',
 'Binny',
 'Watson',
 'Watson',
 'Binny',
 'Watson',
 'Watson',
 'Watson',
 'Binny',
 'Watson',
 'Watson',
 'Watson',
 'Binny',
 'Binny',
 'Binny',
 'Binny',
 'Watson',
 'Binny',
 'Binny',
 'Watson',
 'Watson',
 'Aravind',
 'Aravind',
 'Aravind',
 'Mills',
 'Mills',
 'Mills',
 'Chahal',
 'Mills',
 'Mills',
 'Chahal',
 'Chahal',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Chahal',
 'Chahal',
 'Buttler',
 'Buttler',
 'Buttler',
 'Patel',
 'Buttler',
 'Buttler',
 'Buttler',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Sharma',
 'Buttler',
 'Buttler',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Buttler',
 'Buttler',
 'Buttler',
 'Buttler',
 'Rana',
 'Rana',
 'Rana',
 'Rayudu',
 'Rana',
 'Rana',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rayudu',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rana',
 'Rana',
 'Rayudu',
 'Rana',
 'Rayudu',
 'Rayudu',
 'Rayudu',
 'Rayudu',
 'Rana',
 'Rana',
 'Pandya',
 'Rana',
 'Pandya',
 'Pandya',
 'Rana',
 'Pandya',
 'Pandya',
 'Rana',
 'Pandya',
 'Pandya',
 'Rana',
 'Pandya',
 'Rana',
 'Pollard',
 'Rana',
 'Pollard',
 'Rana',
 'Rana',
 'Rana',
 'Rana',
 'Pollard',
 'Pollard',
 'Rana',
 'Rana',
 'Rana',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pandya',
 'Pandya',
 'Pollard',
 'Pandya',
 'Pollard',
 'Pandya',
 'Pandya',
 'Pollard',
 'Pollard',
 'Pandya',
 'Pandya',
 'Pollard',
 'Pollard',
 'Pandya',
 'Pollard',
 'Pandya',
 'Pandya',
 'Southee',
 'Pandya',
 'Pandya',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'McClenaghan',
 'Agarwal',
 'Rahane',
 'Rahane',
 'Rahane',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Rahane',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Agarwal',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Stokes',
 'Stokes',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Stokes',
 'Smith',
 'Smith',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Smith',
 'Stokes',
 'Stokes',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Stokes',
 'Stokes',
 'Smith',
 'Stokes',
 'Stokes',
 'Smith',
 'Smith',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Dhoni',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Dhoni',
 'Dhoni',
 'Dhoni',
 'Smith',
 'Smith',
 'Dhoni',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Dhoni',
 'Smith',
 'Dhoni',
 'Dhoni',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'Roy',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'Roy',
 'Roy',
 'Roy',
 'Roy',
 'Roy',
 'McCullum',
 'Roy',
 'McCullum',
 'McCullum',
 'McCullum',
 'Raina',
 'Raina',
 'Raina',
 'McCullum',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'Raina',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'McCullum',
 'Raina',
 'Raina',
 'McCullum',
 'Raina',
 'Raina',
 'Raina',
 'McCullum',
 'Raina',
 'Raina',
 'McCullum',
 'Raina',
 'McCullum',
 'Raina',
 'Raina',
 'Finch',
 'Raina',
 'Raina',
 'Finch',
 'Finch',
 'Raina',
 'Raina',
 'Raina',
 'Finch',
 'Raina',
 'Finch',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Karthik',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Karthik',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Karthik',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Karthik',
 'Karthik',
 'Karthik',
 'Raina',
 'Karthik',
 'Karthik',
 'Raina',
 'Raina',
 'Raina',
 'Karthik',
 'Raina',
 'Karthik',
 'Raina',
 'Raina',
 'Raina',
 'Smith',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Lynn',
 'Lynn',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Lynn',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Gambhir',
 'Agarwal',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Rahane',
 'Rahane',
 'Rahane',
 'Rahane',
 'Smith',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Smith',
 'Stokes',
 'Smith',
 'Stokes',
 'Smith',
 'Stokes',
 'Stokes',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Stokes',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Stokes',
 'Dhoni',
 'Stokes',
 'Stokes',
 'Dhoni',
 'Dhoni',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Stokes',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Christian',
 'Tiwary',
 'Christian',
 'Christian',
 'Tiwary',
 'Christian',
 'Christian',
 'Christian',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Tiwary',
 'Bhatia',
 'Vohra',
 'Vohra',
 'Vohra',
 'Vohra',
 'Amla',
 'Vohra',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Vohra',
 'Amla',
 'Amla',
 'Vohra',
 'Amla',
 'Amla',
 'Vohra',
 'Amla',
 'Amla',
 'Saha',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Saha',
 'Saha',
 'Amla',
 'Saha',
 'Saha',
 'Amla',
 'Amla',
 'Amla',
 'Saha',
 'Amla',
 'Amla',
 'Patel',
 'Amla',
 'Amla',
 'Amla',
 'Patel',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Patel',
 'Patel',
 'Amla',
 'Patel',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Patel',
 'Amla',
 'Amla',
 'Amla',
 'Amla',
 'Patel',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Maxwell',
 'Miller',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Miller',
 'Maxwell',
 'Miller',
 'Miller',
 'Maxwell',
 'Miller',
 'Miller',
 'Miller',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Maxwell',
 'Miller',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Maxwell',
 'Miller',
 'Miller',
 'Watson',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Gayle',
 'Watson',
 'Watson',
 'Watson',
 'Gayle',
 'Gayle',
 'Watson',
 'Watson',
 'Watson',
 'Gayle',
 'Gayle',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Watson',
 'Watson',
 'Singh',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Jadhav',
 'Watson',
 ...]

In [224]:
delivs["bowler"] = delivs["bowler"].apply(surname)
list(delivs["bowler"])

['Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Head',
 'Head',
 'Head',
 'Head',
 'Head',
 'Head',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Binny',
 'Binny',
 'Binny',
 'Binny',
 'Binny',
 'Binny',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Aravind',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Chahal',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Choudhary',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Mills',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Watson',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Hooda',
 'Hooda',
 'Hooda',
 'Hooda',
 'Hooda',
 'Hooda',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Henriques',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Nehra',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Cutting',
 'Cutting',
 'Cutting',
 'Cutting',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Zampa',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pollard',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Southee',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Pandya',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'McClenaghan',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Bumrah',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pollard',
 'Pollard',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Pathan',
 'Pathan',
 'Pathan',
 'Pathan',
 'Pathan',
 'Pathan',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Narine',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Yadav',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Chawla',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Woakes',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Boult',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Smith',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Gony',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Jakati',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kumar',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kaushik',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Kulkarni',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Singh',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Natarajan',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Stoinis',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Patel',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Sharma',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Christian',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Bhatia',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Tahir',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Chahar',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Dinda',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Stokes',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Khan',
 'Morris',
 'Morris',
 'Morris',
 'Morris',
 'Morris',
 'Morris',
 'Cummins',
 'Cummins',
 'Cummins',
 'Cummins',
 'Cummins',
 'Cummins',
 'Cummins',
 'Morris',
 'Morris',
 'Morris',
 'Morris',
 'Morris',
 'Morris',
 'Nadeem',
 'Nadeem',
 'Nadeem',
 'Nadeem',
 'Nadeem',
 'Nadeem',
 'Nadeem',
 'Cummins',
 'Cummins',
 'Cummins',
 'Cummins',
 'Cummins',
 'Cummins',
 'Nadeem',
 'Nadeem',
 ...]

In [225]:
auct = auct.replace(['-'],'0')
auct = auct.fillna(0)

In [226]:
auct.tail(10)

,Is Captain(1=yes),Is Wktkeeper(1=Yes),Nationality(1=Overseas),Name,Team,IPL 4 Franchise,Player cost USD,matches,innings played,no,...,wkts taken,Best innings bowling,best match bowling,Bowling average,Bowling econ,sr,4w,5w,10 wicket hauls,Retained
Variable Tag,,,,,,,,,,,,,,,,,,,,,
120.0,1.0,0.0,0,Tendulkar,India,Mumbai Indians,1800000.0,60.0,60.0,8.0,...,2,2011-12-01 00:00:00,2011-12-01 00:00:00,61.50,7.93,46.5,0,0,0,1
121.0,1.0,0.0,1,Warne,Australia,Rajasthan Royals,1800000.0,58.0,31.0,9.0,...,59,2021-04-01 00:00:00,2021-04-01 00:00:00,25.79,7.21,21.4,1,0,0,1
122.0,0.0,0.0,0,Kohli,India,Royal Challengers Bangalore,1800000.0,79.0,70.0,12.0,...,4,2025-02-01 00:00:00,2025-02-01 00:00:00,89.50,8.52,63,0,0,0,1
123.0,1.0,0.0,0,Sehwag,India,Delhi Daredevils,1800000.0,77.0,76.0,4.0,...,19,2014-03-01 00:00:00,2014-03-01 00:00:00,20.68,8.07,15.3,0,0,0,1
124.0,1.0,0.0,0,Singh,India,Pune Warriors,1800000.0,93.0,90.0,12.0,...,40,2029-04-01 00:00:00,2029-04-01 00:00:00,22.30,7.25,18.4,1,0,0,0
125.0,0.0,0.0,0,Pathan,India,Delhi Daredevils,1900000.0,83.0,67.0,23.0,...,89,2027-04-01 00:00:00,2027-04-01 00:00:00,24.29,7.65,19,1,0,0,0
126.0,0.0,0.0,0,Sharma,India,Mumbai Indians,2000000.0,97.0,91.0,18.0,...,26,2011-06-04 00:00:00,2011-06-04 00:00:00,25.19,7.44,20.3,1,0,0,0
127.0,0.0,1.0,0,Uthappa,India,Pune Warriors,2100000.0,93.0,87.0,14.0,...,0,0,0,0.00,0,0,0,0,0,0
128.0,0.0,0.0,0,Pathan,India,Kolkata Knight Riders,2100000.0,90.0,82.0,10.0,...,67,2011-10-04 00:00:00,2011-10-04 00:00:00,24.50,7.46,19.7,2,0,0,0
129.0,1.0,0.0,0,Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,9.0,...,0,0,0,0.00,0,0,0,0,0,0

In [227]:
auct = auct.drop(auct.columns[24], axis=1)
auct = auct.drop(['matches played'], axis=1)

In [228]:
auct = auct.drop(auct.columns[24], axis=1)

In [229]:
auct = auct.drop(['Best innings bowling', 'best match bowling'], axis=1)

In [230]:
list(auct.columns)

['Is Captain(1=yes)',
 'Is Wktkeeper(1=Yes)',
 'Nationality(1=Overseas)',
 'Name',
 'Team',
 'IPL 4 Franchise',
 'Player cost USD',
 'matches',
 'innings played',
 'no',
 'runs scored',
 'highest score',
 'Is star batsman',
 'Is batsman',
 'Batting avg',
 'Balls faced',
 'Strike rate',
 '100 runs made',
 '50 runs made',
 '4s',
 '6s',
 'Catches per match',
 'Catches taken',
 'stumping made',
 'Is bowler?',
 'Number of balls bowled',
 'runs given',
 'Is star bowler',
 'wkts taken',
 'Bowling average',
 'Bowling econ',
 'sr',
 '4w',
 '5w',
 '10 wicket hauls',
 'Retained']

In [233]:
ballbyball = delivs.query('match_id >= 175 and match_id <= 234')
ballbyball

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
40957,175,1,Kolkata Knight Riders,Deccan Chargers,1,1,Tiwary,Hodge,Vaas,0,...,0,0,0,0,0,0,0,MK Tiwary,caught,RG Sharma
40958,175,1,Kolkata Knight Riders,Deccan Chargers,1,2,Ganguly,Hodge,Vaas,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
40959,175,1,Kolkata Knight Riders,Deccan Chargers,1,3,Ganguly,Hodge,Vaas,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
40960,175,1,Kolkata Knight Riders,Deccan Chargers,1,4,Ganguly,Hodge,Vaas,0,...,0,0,0,0,0,0,0,SC Ganguly,caught,Anirudh Singh
40961,175,1,Kolkata Knight Riders,Deccan Chargers,1,5,Pujara,Hodge,Vaas,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55450,234,2,Mumbai Indians,Chennai Super Kings,20,2,Khan,Malinga,Bollinger,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
55451,234,2,Mumbai Indians,Chennai Super Kings,20,3,Khan,Malinga,Bollinger,0,...,0,0,0,0,1,0,1,Z Khan,run out,R Ashwin
55452,234,2,Mumbai Indians,Chennai Super Kings,20,4,Fernando,Malinga,Bollinger,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
55453,234,2,Mumbai Indians,Chennai Super Kings,20,5,Malinga,Fernando,Bollinger,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
55454,234,2,Mumbai Indians,Chennai Super Kings,20,6,Fernando,Malinga,Bollinger,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [234]:
clean_data = auct.merge(ballbyball, left_on='Name', right_on='batsman')
clean_data

,Is Captain(1=yes),Is Wktkeeper(1=Yes),Nationality(1=Overseas),Name,Team,IPL 4 Franchise,Player cost USD,matches,innings played,no,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,0.0,0.0,1,Bailey,Australia,Chennai Super Kings,50000.0,32.0,28.0,4.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,0.0,0.0,1,Bailey,Australia,Chennai Super Kings,50000.0,32.0,28.0,4.0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2,0.0,0.0,1,Bailey,Australia,Chennai Super Kings,50000.0,32.0,28.0,4.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
3,0.0,0.0,1,Bailey,Australia,Chennai Super Kings,50000.0,32.0,28.0,4.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,0.0,0.0,1,Bailey,Australia,Chennai Super Kings,50000.0,32.0,28.0,4.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13848,1.0,0.0,0,Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,9.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13849,1.0,0.0,0,Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,9.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13850,1.0,0.0,0,Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,9.0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
13851,1.0,0.0,0,Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,9.0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13852,1.0,0.0,0,Gambhir,India,Kolkata Knight Riders,2400000.0,87.0,85.0,9.0,...,0,0,0,0,0,0,0,G Gambhir,caught,RG Sharma